import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Inter } from "@next/font/google";
import DLSU from "../components/Calculator";
import Calculator from "../components/Calculator";
import Description from "../components/Description";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Grade Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Description />
      <Calculator />
    </>
  );
}
